version: '1'

volumes:
  postgres_volume:

services:
  bot:
    build: .
    container_name: tg_bot
    restart: always
    environment:
      API_TELEGRAM: ${API_TELEGRAM}
      API_GPT: ${API_GPT}
      ORGANIZATION: ${ORGANIZATION}
      USERNAME_SQL: ${USERNAME_SQL}
      PASSWORD: ${PASSWORD}
      DB: postgresql
      DB_LOGIN: ${DB_LOGIN}
      DB_PASS: ${DB_PASS}
      DB_HOST: postgres_server
      DB_NAME: db_bot
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres_server
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: db_bot
