"""migration 2

Revision ID: 6a7e93e93744
Revises: 687de75e37ce
Create Date: 2023-05-01 18:01:28.410956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import ForeignKeyConstraint

# revision identifiers, used by Alembic.
revision = '6a7e93e93744'
down_revision = '687de75e37ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('chats', 'chat_id')
    op.create_primary_key('chats_pk', 'chats', ['id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    op.add_column('chats', sa.Column('chat_id', sa.INTEGER(),
                                     server_default=sa.text("nextval('chats_chat_id_seq'::regclass)"),
                                     autoincrement=True, nullable=False))
    op.drop_column('chats', 'id')
    # ### end Alembic commands ###
